### ISSUE TITLE
Doubts stringmetric-cli

### ISSUE THREAD

**Issue by luizchaves** [rockymadden/stringmetric#1]
How do i configure stringmetric-cli to use command line interface?

**Comment by rockymadden** [comment]
The CLI has to be built via Gradle to interact with them in a shell. Here are the steps:

```
git clone https://github.com/rockymadden/stringmetric.git
cd stringmetric
gradle :stringmetric-cli:tar
```

Doing that will create a "build" directory with a subdirectory called "stringmetric-cli" under the "cli" directory in the base of the project. To run a command from the current directory that you would be in from doing the above:

```
./cli/build/stringmetric-cli/jaroMetric abc xyz
```

OR

```
cd ./cli/build/stringmetric
./jaroMetric abc xyz
```

You can move said "stringmetric-cli" directory files wherever you want (there is also a tar of them that the Gradle command creates). Lastly, you will likely need to chmod them because of my inability to do so via Gradle (well, I issue the command but it doesnt seem to work).

**Comment by rockymadden** [comment]
Let me know if this does not work for you. Otherwise, I will close in a few days if I haven't heard back (I'd assume you were successful). Thanks for asking! I will put this in the readme on the next version.

:+1:

**Comment by luizchaves** [comment]
Thanks for the answer because it I can run stringmetric-cli, but the file gradle.properties was generating error in gradle (specifically in daemon) then I delete it and got success.

**Comment by rockymadden** [comment]
Happy to hear it worked! Do you happen to run a 32-bit OS or have 2GB or less of RAM? If so, there is a setting in that properties file that would cause issues. Xmx=2048

**Comment by luizchaves** [comment]
Really, the PC that I used had 2GB! And by reducing the size the execution was successful. Thanks for answer.

**Comment by rockymadden** [comment]
Sure thing! Thanks again for the submission, I'll get the updated documentation into v0.26.0.
